version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency_name: "*"
    groups:
      all-dev-dependencies:
        patterns:
          - "*"
      major-updates:
        patterns:
          - "*"
      testing-tools:
        patterns:
          - "*"
