version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '09:00'
      timezone: 'Europe/Madrid'
    open-pull-requests-limit: 3
    assignees:
      - 'r3nya'

  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '09:00'
      timezone: 'Europe/Madrid'
    open-pull-requests-limit: 3
    groups:
      production:
        dependency-type: 'production'
        update-types:
          - 'minor'
          - 'patch'
      development:
        dependency-type: 'development'
        update-types:
          - 'minor'
          - 'patch'
    assignees:
      - 'r3nya'
